### PR TITLE
Add Verbosity options to commands

### PR DESCRIPTION
**Pull request by pfaffenrodt**
use -v or --verbose to write actual command
use -vv to print also raw command output

#20 

## Note
Symfony Process has no option to create actual command line.  
Also all related methods are private (used reflection to replace variables).  
Replace `ConsoleOutput`  with `OutputInterface`, because ConsoleOutput had wrong settings of verbosity.

### CODE REVIEW

**Comment by sinnbeck** [comment]
Very nice solution. Can get a bit verbose for some commands, so I might choose to break up some none verbose alternatives.

I like that you chose to use reflection to tab into symfony instead of trying to write you own 

Did you forget to remove this code snippet? Seems unused :) Apart from that, all is good.

```
protected function internal_replacePlaceholders($command, $env = []) {
        return $this->privateMethod($this, 'replacePlaceholders')->invoke($this);
    }

**Review by sinnbeck — APPROVED** [review]
Like the implementation.I might make a few changes as not all commands makes sense to output.

Thanks for the effort! Great work!

**Comment by pfaffenrodt** [comment]
> Very nice solution. Can get a bit verbose for some commands, so I might choose to break up some none verbose alternatives.
> 
> I like that you chose to use reflection to tab into symfony instead of trying to write you own
> 
> Did you forget to remove this code snippet? Seems unused :) Apart from that, all is good.
> 
> ```
> protected function internal_replacePlaceholders($command, $env = []) {
>         return $this->privateMethod($this, 'replacePlaceholders')->invoke($this);
>     }
> ```

I forgot to replace the related call `$this->privateMethod($this, 'replacePlaceholders')->invoke($this, $command, $env);` with `internal_replacePlaceholders`

**Comment by sinnbeck** [comment]
I misread the instructions. Thought they meant labels on issues. Added 
to the project now also

**Pull request merged**
