### PR TITLE
Adds wrappers for artisan command tests

### PR DESCRIPTION
**Pull request by iammikek**
Starting to look at how we can get test coverage in place.

### CODE REVIEW

**Comment by sinnbeck** [comment]
Thanks. Just curious. What is the idea of testing if the classes exists?

**Comment by sinnbeck** [comment]
I have added a couple of tests and merged into master. Feel free to base your testing on those :)

**Comment by iammikek** [comment]
Great stuff.
I’ll give those a look.

**Comment by sinnbeck** [comment]
@iammikek Can you merge master and push again? :)

**Pull request closed without merging**
